trigger:
- main

pool:
  name: SelfHostedPool

stages:
- stage: Build
  jobs:
  - job: FirstJob
    steps:
    - powershell: echo Build FirstJob
    - powershell: echo $(PipeLineLevelVariable)
    - powershell: echo $(Build.BuildNumber)
    - powershell: echo $(Build.BuildId)
    - powershell: echo $(Build.SourceBranchName)
    - powershell: echo $(Build.SourcesDirectory)
    - powershell: echo $(System.DefaultWorkingDirectory)
    - powershell: ls -Recurse $(System.DefaultWorkingDirectory)
    - powershell: echo $(Build.ArtifactStagingDirectory)
    - powershell: echo java -version
    - powershell: echo node --version
    - powershell: echo python -version
    - powershell: echo mvn -version
    - powershell: echo $(Build.ArtifactStagingDirectory)
    - task: CopyFiles@2
      inputs:
        SourceFolder: '$(System.DefaultWorkingDirectory)'
        Contents: |
          **/*.yaml
          **/*.tf
        TargetFolder: '$(Build.ArtifactStagingDirectory)'
    - powershell: echo $(Build.ArtifactStagingDirectory)
  # - job: SecondJob
  #   steps:
  #   - powershell: echo Build SecondJob
# - stage: DevDeploy
#   variables:
#     environment: Dev
#   dependsOn: Build
#   jobs:
#   - job: DevDeployJob
#     steps:
#     - powershell: echo $(environment)DeployJob
# - stage: QADeploy
#   variables:
#     environment: QA
#   dependsOn: Build
#   jobs:
#   - job: QADeployJob
#     steps:
#     - powershell: echo $(environment)DeployJob
# - stage: ProdDeploy
#   dependsOn:
#   - DevDeploy
#   - QADeploy
#   jobs:
#   - job: ProdDeployJob
#     steps:
#     - powershell: echo ProdDeployJob
