trigger:
- main

pool:
  name: SelfHostedPool

stages:
- stage: Build
  jobs:
  - job: FirstJob
    steps:
    - powershell: |
        Write-Host "Build FirstJob"
  - job: SecondJob
    steps:
    - powershell: |
        Write-Host "Build SecondJob"
- stage: DevDeploy
  jobs:
  - job: DevDeployJob
    steps:
    - powershell: |
        Write-Host "Build DevDeployJob"
- stage: QADeploy
  jobs:
  - job: QADeployJob
    steps:
    - powershell: |
        Write-Host "Build QADeployJob"
- stage: ProdDeploy
  jobs:
  - job: ProdDeployJob
    steps:
    - powershell: |
        Write-Host "Build ProdDeployJob"
