trigger:
- main

pool:
  name: SelfHostedPool

stages:
- stage: Build
  jobs:
  - job: FirstJob
    steps:
    - powershell: echo Build FirstJob
  - job: SecondJob
    steps:
    - powershell: echo Build SecondJob
- stage: DevDeploy
  dependsOn: Build
  jobs:
  - job: DevDeployJob
    steps:
    - powershell: echo Build DevDeployJob
- stage: QADeploy
  dependsOn: Build
  jobs:
  - job: QADeployJob
    steps:
    - powershell: echo "Build QADeployJob"
- stage: ProdDeploy
  dependsOn:
  - DevDeploy
  - QADeploy
  jobs:
  - job: ProdDeployJob
    steps:
    - powershell: echo Build ProdDeployJob
