trigger:
- main

# strategy:
#   matrix:
#     linux:
#       operatingSystem: 'SelfHostedPool'
#     mac:
#       operatingSystem: 'SelfHostedPool'

pool:
  name: SelfHostedPool


stages:
- stage: Build
  jobs:
  - job: BuildJob
    steps:
    - powershell: echo Do the build
- stage: DevDeploy
  jobs:
  - deployment: DevDeployJob
    environment: Dev
    strategy:
     runOnce:
       deploy:
         steps:
           - script: echo deploy to Dev
- stage: QADeploy
  jobs:
  - deployment: DevDeployJob
    environment: QA
    strategy:
     runOnce:
       deploy:
         steps:
           - script: echo deploy to Dev